<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK8LYstQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK8LYstQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK8LYstQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK8LYstQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK8LYstQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'K8LYstQ',
    'container.build_id' => 'ebfa04e3',
    'container.build_time' => 1721744168,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK8LYstQ');
